version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - arangodb
  arangodb:
    image: arangodb:3.8
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
